name: cyber_cop_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: any
  firebase_core: any
  firebase_analytics: any
  firebase_database: any
  flutter_map: any
  cloud_firestore: any

  google_sign_in: any

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  pin_entry_text_field: ^0.1.4
  card_settings: ^1.5.5
  animated_text_kit: ^2.0.0
  double_back_to_close_app: ^0.1.2
  image_picker: ^0.6.3+1
  rflutter_alert: ^1.0.3
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
    - assets/
    - images/
  fonts:
    - family: LakkiReddy
      fonts:
        - asset: fonts/LakkiReddy-Regular.ttf
    - family: RubikMonoOne
      fonts:
        - asset: fonts/Merriweather-Bold.ttf


